### ISSUE TITLE
got this error

### ISSUE THREAD

**Issue by dovanchan** [Dawars/SqueezeNet-tf#5]
Hi,when I try to run the SqueezeNet.py ,I got this error
DOVANtekiMacBook-Pro:SqueezeNet-tf-master DOVAN$ python SqueezeNet.py 
Traceback (most recent call last):
  File "SqueezeNet.py", line 169, in <module>
    net  = SqueezeNet(sess, alpha)
  File "SqueezeNet.py", line 24, in __init__
    self.build_model()
  File "SqueezeNet.py", line 46, in build_model
    net['fire2'] = self.fire_module('fire2', net['pool1'], self.sq_ratio * 16, 64, 64)
  File "SqueezeNet.py", line 138, in fire_module
    name=layer_name + '_fire_bias_e3' ))], 3)
  File "/Users/DOVAN/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1075, in concat
    dtype=dtypes.int32).get_shape(
  File "/Users/DOVAN/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/DOVAN/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/DOVAN/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Users/DOVAN/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/Users/DOVAN/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

Can you help me to point out what's wrong with it?

**Comment by Dawars** [comment]
I see from the error that you are using anaconda with python 2, this was written in Python 3. This may not be the problem though.

Can you tell me which tensorflow (cuda?) version you are using?

**Comment by dovanchan** [comment]
Hi,I am using tensorflow1.0 with cuda8.0,I will try to use python3 now
